- README.md
I have added instructions for different OS systems to install xampp. See if it's helpful and let me know if I need to make any changes.
> Add instructions for different OS in Readme

- .gitignore
- README.md
- config/google.js
- config/local.js
- routes/profile.js
- routes/route.js
- schema/project.js
- schema/user.js
- server.js
- views/all.ejs
- views/css/autocomplete.css
- views/front.ejs
- views/js/autocomplete.js
- views/js/index.js
local strategy for login and search for username, email and project name implemented
> local strategy and search implemented

- views/css/dashboard.css
- views/dashboard.ejs
a small portion is left which will show repos liked, shared and viewed by user
> User dashboard added

- config/google.js
- package-lock.json
- package.json
- routes/profile.js
- routes/route.js
- server.js
- views/home.ejs
implementation of crypt for passwords at issue #14
> Implement Bcrypt

- views/community_dashboard.ejs
- views/css/comm_dashboard.css
> Adding community dashboard

- config/credential.js
- config/facebook.js
- config/github.js
- package-lock.json
- package.json
- routes/login.routes.js
- schema/user.js
- server.js
- views/all.ejs
> Facebook Login Setup

- views/css/codeuino.css
- views/index.html
- views/js/codeuino.js
> Login Sign up modal added with github, google and email buttons

- views/css/codeuino.css
- views/css/other-landing.css
- views/other-landing.ejs
Minor changes done on the other-landing page.
> other-landing ejs page updated

- package-lock.json
- package.json
- tests/controller_test.js
I have written the first test for now and it is passing successfully
#75 
Signed-off-by: tushar goel <tushar.goel.dav@gmail.com>
> user added test sucessfully done

- PR_Template.md
The issue being referred to is not being mentioned in the Pull Requests so that auto closing of the issue can happen
`Fixes #110 `
Auto closing of issue will be done whenever the pull request is merged
_**Before** [How was it earlier, add it here]_
_**After** [How it looks now, add it here]_
> Update: Pull Request Template

- views/css/codeuino.css
> fixed frontend responsiveness

- views/other-landing.ejs
_Describe the problem you are trying to achieve. Please provide in detail_
Css was not loading
_**Before** [How was it earlier, add it here]_
give in the issue
_**After** [How it looks now, add it here]_
> css error resolved

- package-lock.json
- server.js
- views/css/error.css
- views/error.ejs
_404 was not rendering on uncaught requests_
_`Fixes #142 `, Refer to this [link](https://github.com/codeuino/Social-Platform-Donut/issues/142)_
_Added error page and then rendered on uncaught requests_
_**Before** Only message was coming like `can't get URL`_
_**After** ![error1](https://user-images.githubusercontent.com/31209617/54076834-ce698580-42d5-11e9-951d-a7bfb55fab98.png)_
> added error page for uncaught requests

- views/css/other-landing.css
- views/other-landing.ejs
_Describe the problem you are trying to achieve. Please provide in detail_
`Fixes #80 `, Refer to this [link](https://github.com/codeuino/Social-Platform-Donut/issues/80) for more details_
Used bootstrap 4 form  control and little bit of css. Stylesheet was not linked correctly so fixed stylesheet path,
> improved search button styling

- controller/profile.controller.js
- package-lock.json
- package.json
- server.js
_There was no validation for submitting a project form_
_`Fixes #149 `, Refer to this [link](https://github.com/codeuino/Social-Platform-Donut/issues/149) for more details_
_Solved using express validator_
_**Before** [How was it earlier, add it here]_
_**After** [How it looks now, add it here]_
@capedcrusader23  please check the code once and let me know if there is any problem .
> [WIP] added backend validation for project submit form

- Contributing.md
- routes/login.routes.js
Contributing.md is added
Fixes issue #184 .
A small Guide for new comers
Contributing.ms is created
- Addition of new file
- My code follow the same style as the codebase
- My Code changed required change in documentation
- I have updated the Readme accordingly
- I made PR within **development branch only**
> Contributing.md is created

- client/package.json
- client/src/App.vue
- client/src/components/Login.vue
- client/src/components/Signup.vue
- client/src/router.js
- client/src/store/state.js
- client/src/views/Welcome.vue
Login module is done.
Signup module is integrated, but not completed.
> Login and signup module is created and login module is done

- client/.eslintrc.js
- client/src/App.vue
- client/src/components/CreatePost.vue
- client/src/components/LandingScreen.vue
- client/src/components/Login.vue
- client/src/components/NavigationBar.vue
- client/src/components/Newsletter.vue
- client/src/components/PortfolioStarterForm.vue
- client/src/components/Post.vue
- client/src/components/ProfileSettings.vue
- client/src/components/ProjectScreen.vue
- client/src/components/Signup.vue
- client/src/components/Userdetail.vue
- client/src/components/singlePost.vue
- client/src/router.js
- client/src/service-worker.js
- client/src/views/Feed.vue
- client/src/views/Home.vue
- client/src/views/Portfolio.vue
- client/src/views/ProfileView.vue
- client/src/views/Settings.vue
- The dark mode is added to all pages.
- Console messages are removed
- NavBar is now fixed in position.
- Changed routes for "/" to "/feed/:id" for feed
- Added Home.vue (test) for "/"
- Refactored validation in Login and Signup, before the invalid email message was displaying for empty email, now it doesn't.
I will be uploading screenshots asap.
> Dark mode added to all pages and console messages are removed

- .gitignore
- package.json
- server/README.md
- server/controller/posts.js
- server/routes/index.routes.js
- server/routes/posts.route.js
- server/schema/posts.js
- server/server.js
Signed-off-by: tushar goel <tushar.goel.dav@gmail.com>
> All features for post added

- server/README.md
I made installation guide for serverside. 
@vaibhavdaren
> Updated README.md for server side.

- server/controller/forgotpass.controller.js
- server/routes/forgotpass.routes.js
- server/routes/index.routes.js
> logic for forgot password created 

- server/tests/todos.test.js
**Added tests for todos tasks API**
Please review @vaibhavdaren @devesh-verma
> added tests for todos tasks -all passing

- server/controller/forgotpass.controller.js
- server/package.json
- server/routes/forgotpass.routes.js
- server/tests/todos.test.js
Refactored testing code and removed errors related to credantial.js
> removed development branch bugs, refactored the code

- server/tests/profile.test.js
**Added tests for profile routes -> Passing tests**
@vaibhavdaren plz review. Used assertion as well.
> added test for the profile routes

- server/controller/todos.controller.js
- server/tests/todos.test.js
Fixed #240 and updated the test code accordingly. 
Here the screenshot of passing todo's tests after refactoring todos controller
> refactored the todo controller and fixed the todo's test accordingly

- README.md
- client/README.md
- server/README.md
- server/server.js
Fixes #237    Changed the vague documentation in  all readme files.
> Changed the Documentation in README.md file.

- server/middleware/bucket.js
- server/middleware/token-bucket.js
> Enhancement : Rate limiter token-bucket added

- server/middleware/image_upload.js
Created a middleware for the backend to uploading images.
> Solves issue #222

- client/src/components/PortfolioStarterForm.vue
- client/src/views/Portfolio.vue
Fixes the console errors on the portfolio page as per #260.
> Fix portfolio page errors, fixes #260

- .browserslistrc
- src/router.js
- src/user/dashboard/dashboard.js
- src/user/dashboard/navigation/navigation.js
- src/user/orginization/org-info/org-info.js
- src/user/orginization/org-info/org-info.scss
- src/user/orginization/orginization.js
- src/user/orginization/orginization.scss
- src/user/pinned-posts/pinned-posts.js
- src/user/pinned-posts/pinned-posts.scss
- src/user/pinned-posts/posts/posts.js
- src/user/pinned-posts/posts/posts.scss
- src/user/profile/profile.js
- src/user/profile/profile.scss
- src/user/profile/user-info/user-info.js
- src/user/profile/user-info/user-info.scss
> adds profile page and pinned post

- src/user/dashboard/news-feed/news-feed.js
- src/user/dashboard/news-feed/news-feed.scss
> Improved post input box and added event and project icons.

- build.sh
- package.json
Fixes #331 
@jaskirat2000 please review this
> Fix netlify react-router issue

- package-lock.json
- package.json
- src/common/Popups.js
- src/router.js
- src/user/dashboard/navigation/navigation.js
- src/user/dashboard/settings/SettingContent.js
- src/user/dashboard/settings/Settings.js
- src/user/dashboard/settings/layouts/SettingSidebar.js
- src/user/dashboard/settings/styles/settings.scss
Added initial settings page for the users (Reference used: Facebook settings page) 
**Screenshot**
No hardcoded data is used(except default data), keeping the components open for receiving data from API.
Fixes #335 
@vaibhavdaren @jaskirat2000 Please review
> Added initial settings page for the users (Reference used : Facebook settings page) 

- public/index.html
- src/user/dashboard/navigation/navigation.js
- src/user/dashboard/navigation/navigation.scss
- src/user/integrations/Jitsi.js
- src/user/integrations/JitsiApi.js
- src/user/integrations/NameForm.js
- src/user/integrations/jitsi.scss
Fixes #353 
I have created a basic integration of Jitsi Meet using JitsiMeetAPI.
> Added Jitsi Meet Integration

- src/common/Popups.js
Fixes issue #396
New changes looks like
> Removed the unnecessary close button in pop-ups of settings [FRONTEND]

- src/jsonData/organization-updates.js
- src/user/dashboard/updates/updates.js
- src/user/dashboard/updates/updates.scss
Fixes Issue #418 
Also, upgraded the frontend of organization updates section with material-UI
New Changes looks like
> Added the json-data file for organization updates along with the material-ui 

- src/jsonData/portfolio-feed.js
- src/user/dashboard/portfolio/portfolio.js
- src/user/dashboard/portfolio/portfolio.scss
> Added portfolio JSON and changed the UI to material-UI

- src/user/dashboard/navigation/navigation.js
- src/user/dashboard/settings/SettingContent.js
- src/user/dashboard/settings/layouts/RightNav.js
- src/user/dashboard/settings/styles/settings.scss
> Converting Settings page to Material UI

- package.json
- src/actions/authAction.js
- src/auth/signup-form/signup-form.js
- src/auth/signup-form/signup-form.scss
Fixes Issue : #375 
**Filling the signup form**
**creation of account in backend**
> Added the updated fields in the signup page using Material-UI 

- src/auth/login-form/login-form.js
- src/auth/login-form/login-form.scss
- src/common/Popups.js
> Added UI for forgot password

- src/jsonData/comments.js
- src/user/dashboard/news-feed/news-feed.js
- src/user/dashboard/news-feed/popups/comment.js
- src/user/dashboard/news-feed/popups/comment.scss
> Added pop-up for comment 

- src/auth/login-form/login-form.js
- src/auth/login-form/login-form.scss
Fixes issue #439 
New Changes looks like
> Updation of login form to material-ui [MATERIAL-UI]

- src/user/dashboard/navigation/navigation.js
- src/user/profile/popups/edit-profile.js
- src/user/profile/popups/followers.js
- src/user/profile/popups/logout.js
- src/user/profile/popups/popups.scss
- src/user/profile/user-info/user-info.js
The popups associated with Profile page have been enhanced using Material UI.
> Improved Profile Popups to Material UI

- package-lock.json
- src/actions/authAction.js
- src/actions/types.js
- src/auth/login-form/login-form.js
- src/common/Popups.js
- src/reducers/errorReducer.js
- src/reducers/index.js
- src/reducers/requestStatus.js
- src/store.js
- src/utils/setRequestStatus.js
Fixes #441
**PR includes** 
1. (**WIP**) integrated functionality of forgot password and fixed bugs (redux devtool => was causing an error if that is not installed on the browser, now this is fixed ) 
2. Refactored state.
3. Reducers for backend request state management, so that in between the request process we can show the indicators accordingly
4. Formatted some shitty codes.
>  integrated functionality of forgot password and fixed bugs (redux devtool) 

- src/auth/login-form/login-form.js
- src/auth/login-form/login-form.scss
- src/auth/login/login.js
- src/auth/login/login.scss
- src/auth/signup-form/signup-form.js
- src/auth/signup-form/signup-form.scss
- src/user/dashboard/dashboard.scss
- src/user/dashboard/navigation/navigation.js
- src/user/dashboard/navigation/navigation.scss
- src/user/dashboard/news-feed/news-feed.js
- src/user/dashboard/news-feed/news-feed.scss
- src/user/dashboard/news-feed/popups/AddEventModal.js
- src/user/dashboard/notifications/notifications.scss
- src/user/dashboard/upcoming-events/upcoming-events.scss
- src/user/dashboard/updates/updates.js
- src/user/dashboard/updates/updates.scss
- src/user/organization/org-info/org-info.js
- src/user/organization/org-info/org-info.scss
- src/user/organization/organization.scss
- src/user/pinned-posts/posts/posts.scss
Fixes #465 
Fixes the inconsistencies mentioned in the [document]( https://docs.google.com/document/d/1yzfLn1_5bLmH-XLnCIYK5B_IUQd6ZhDIvM40ewasTTA/edit)
The fixed tasks are marked in green.
A few remaining tasks are marked ? in red that require further clarificatiion
> Fixing front end inconsistencies

- README.md
- Added correct link to frontend in README.
- Added correct link to Slack channel in community section of README.
> Fixes #491

- README.md
Adding yarn support and providing info in Readme.md
> Updates in Readme.md

- package-lock.json
- package.json
- src/user/dashboard/news-feed/popups/AddPostModal.js
- src/user/proposals/UserProposalDashboard/DashboardRightPanel/Comments/Comments.js
- src/user/proposals/UserProposalDashboard/DashboardRightPanel/DashboardRightPanel.js
Fixes #524 
1) Added Showdown package to the package.json file. For some reason, this was not included there and was causing the dev branch to break. 
2) Removed unused variables in the #501 PR.
3) Removed warnings that are shown in the console for the #501 PR.
> fixing dev branch issues

- src/actions/notificationAction.js
- src/user/proposals/ProposalEditor/EditorContent/DropZone.js
- src/user/proposals/ProposalEditor/EditorContent/EditorContent.js
- src/user/proposals/UserProposalDashboard/DashboardContent/DashboardContent.scss
- src/user/proposals/UserProposalDashboard/DashboardRightPanel/Comments/Comments.js
Fixes the following issues mentioned at #546
> Fixing proposal functionality issues

- src/user/proposals/ProposalEditor/EditorContent/EditorContent.js
- src/user/proposals/ProposalEditor/EditorContent/EditorContent.scss
- src/user/proposals/UserProposalDashboard/DashboardContent/DashboardContent.js
- src/user/proposals/UserProposalDashboard/DashboardContent/DashboardContent.scss
As discussed during the last meeting, this PR focuses on implementing,
1) Pagination on the proposal dashboard page,
2) Fixes the Search bar on the proposal dashboard page. 
3) Fixes some minor issues on the proposal editor page (i.e height between the fields and bold field titles)
Please review @vaibhavdaren @devesh-verma @Rupeshiya.
> Adding pagination to dashboard and minor changes.

- package-lock.json
- src/user/dashboard/news-feed/news-feed.js
- src/user/dashboard/news-feed/popups/PostReactionsModal.js
- src/user/profile/content/PostContent.js
- src/user/profile/profile-feed.js
Fixes Issues caused by the merge of #556 PR.
@vaibhavdaren Please have a look.
> Fixing issues caused by reactions PR

- src/user/dashboard/dashboard.scss
- src/user/dashboard/navigation/navigation.scss
- src/user/dashboard/news-feed/news-feed.js
- src/user/organization/organization.scss
- src/user/profile/profile.scss
- src/user/projects/projects.scss
> Fixing Dashboard navbar issues

- src/user/dashboard/navigation/navigation.js
- src/user/dashboard/navigation/navigation.scss
Fixes #565 
- Now clicking anywhere on items in the navigation menu works
> Fix #565 - Clicking on items in navigation

- src/assets/jsonData/integrations.js
- src/router.js
- src/user/integrations/UserIntegrations/IntegrationDetails.js
- src/user/integrations/UserIntegrations/UserIntegrations.js
- src/user/integrations/UserIntegrations/UserIntegrations.scss
Partially fixes #564
Implements the frontend portion of the user integrations UI as mentioned at, https://www.figma.com/file/iZvb7rLYRp3Di3wILVQ7V9/CodeUino-Donut?node-id=2939%3A6488
I have used dummy data to represent the integrations.
Implemented the Integration details as a separate page as per the discussion with Jaskirat and Siddharth.
@jaskiratsingh2000 Please have a look.
> User Integrations

- src/common/Popups.js
PR includes: 
minor prop fix in common/popups.js
> minor prop fix
